### ISSUE TITLE
Is EINTR handled on POSIX?

### ISSUE THREAD

**Issue by Boris-Barboris** [vibe-d/eventcore#135]
Grep shows that it's not. Learned about this return code the hard way while using std.socket. It definitely breaks synchronous code on long blocking calls, if unhandled.

https://stackoverflow.com/questions/6870158/epoll-wait-fails-due-to-eintr-how-to-remedy-this

**Comment by s-ludwig** [comment]
In case of the epoll code it should be fine, as currently the poll is simply retried in a loop in case of an error return (any of the non-EINTR errors should probably be changed to lead to an assertion failure instead). However, there are quite a few places with other blocking calls that are problematic, such as the read/write calls in `ThreadedFileEventDriver`. 

`ThreadedFileEventDriver` could probably be fixed with an appropriate signal mask for the most part, but the rest of the applicable code needs a careful review to be sure.
