### ISSUE TITLE
LNK4255 warning when compiling examples under Windows 7 x86-64

### ISSUE THREAD

**Issue by unleashy** [vibe-d/eventcore#29]
```
> dub build --arch=x86_64 --single http-server.d
Performing "debug" build using dmd for x86_64.
taggedalgebraic 0.10.7: building configuration "library"...
eventcore 0.8.21: building configuration "winapi"...
http-server-example ~master: building configuration "application"...
Linking...
eventcore.lib(driver.obj) : warning LNK4255: library contain multiple objects of the same name; linking object as if no debug info
```

This is stripping all debug info and making it impossible to have proper stack traces, which is aggravating. If I pass the `--combined` flag to dub, it doesn't output the warning; x86 builds are fine too.

**Comment by s-ludwig** [comment]
I've opened a workaround pull request, but it sounds like this should also be corrected in DMD itself. Since D has a module system, it would make sense to name object files according to their fully qualified name instead of just the module name itself.

**Comment by unleashy** [comment]
@s-ludwig hey, this issue is back unfortunately :grimacing:

**Comment by s-ludwig** [comment]
Noticed that too, a few days ago. The good news is that it only influences debug data for the mentioned module. Everything else works as normal. So if stack traces do not show up, the cause is probably something else.

The right solution to me seems to be to let DMD name the modules according to their package hiearchy (e.g. "eventcore-driver.obj" instead of just "driver.obj"). That would also solve issues surrounding the "-op" switch, which is currently used by DUB to properly build projects that have this kind of name clash.

**Comment by unleashy** [comment]
>The good news is that it only influences debug data for the mentioned module.

Ah, good to know! Stack traces do seem to be working fine, so it's mostly usable. Thanks for coming back to me!
